ALTER TABLE photo DROP COLUMN sales_rep_id;
ALTER TABLE report DROP COLUMN sales_rep_id;
ALTER TABLE client DROP COLUMN sales_rep_id;

ALTER TABLE myclientele_user DROP COLUMN boss_id;

DROP TABLE myclientele_user;

ALTER TABLE client ADD COLUMN sales_rep_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL;

ALTER TABLE report ADD COLUMN sales_rep_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL;

ALTER TABLE photo ADD COLUMN sales_rep_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL;

